//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNS.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int IdEmployee { get; set; }
        public string SurName { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string PassportSerial { get; set; }
        public string PassportNumber { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int Experience { get; set; }
        public string Email { get; set; }
        public int IdGender { get; set; }
        public int IdRole { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Password { get; set; }
        public int IdPost { get; set; }
        public string Photo { get; set; }

        public string FullName { get => $"{Name} {SurName}"; }

        public virtual Gender Gender { get; set; }
        public virtual Post Post { get; set; }
        public virtual Role Role { get; set; }
    }
}
