//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNS.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderStatus
    {
        public int IdOrderStatus { get; set; }
        public int IdOrder { get; set; }
        public int IdStatus { get; set; }
        public System.DateTime DateStatrt { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
