//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNS.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int IdReview { get; set; }
        public string Title { get; set; }
        public int IdOrderProduct { get; set; }
        public System.DateTime Date { get; set; }
        public int Retihg { get; set; }
    
        public virtual OrderProduct OrderProduct { get; set; }
    }
}
