//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNS.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondPhoto
    {
        public int IdSecondPhoto { get; set; }
        public int IdProduct { get; set; }
        public string Photo { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
