//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNS.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Post
    {
        public string FIO { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Position { get; set; }
        public System.DateTime DateStart { get; set; }
    }
}
